---

version: '3.8'

services:
  #
  # PostgreSQL
  #
  autocrypt-pg:
    image: postgres:15-bullseye
    container_name: autocryptor-pg
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: autocryptor-user
      POSTGRES_PASSWORD: autocryptor-pass
      POSTGRES_DB: autocryptor-db
      POSTGRES_INIT_DB_ARGS: --encoding=UTF-8
    volumes:
      - type: bind
        source: ./docker/db/sql/
        target: /docker-entrypoint-initdb.d/